[package]
name = "sapio-trait"
version = "0.2.3"
edition = "2018"
license = "MPL-2.0"
authors = ["Jeremy Rubin <j@rubin.io>"]
repository = "https://github.com/sapio-lang/sapio"
homepage = "https://sapio-lang.org"
description = "A programming framework for bitcoin smart contracts."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0"
serde_derive = "1.0"

[dependencies.sapio-data-repr]
package = "sapio-data-repr"
path = "../sapio-data-repr"
